### ISSUE TITLE
Version Wednesday, October 23, 2019 does not recall volume settings

### ISSUE THREAD

**Issue by Petervos2018** [MarcBoule/MindMeldModular#10]
They are all at 0dB.
(But the solo/fade bug is fixed ;)
Greetings Peter.

**Comment by MarcBoule** [comment]
I can't reproduce this, if I set the fader levels, close Rack, and then re-open it, they are all at their last settings. Can you elaborate on your test?

**Comment by MarcBoule** [comment]
If you had them in a saved patch, with the changes that I made, you may need to re-set the faders levels, and save the patch again, and after that, it should recall them properly. Can you confirm this?

**Comment by Petervos2018** [comment]
Sure download this file from omri, all the sliders are at 0. dB and they should not be.

https://patchstorage.com/mixmaster-from-mindmeld/

**Comment by Petervos2018** [comment]
Sorry I was answering your previous Question,
yes I think that after setting the Sliders again and re-saving it did work.

**Comment by MarcBoule** [comment]
Ok, just tried it, and it does look like my last fix for linked faders makes it such that patches saved in the previous versions will do what you are reporting. I really hate it when patch compatibility is compromised, so will try to add a small change such that when faders are not linked they are reloaded properly. This would at least mitigate that effect a bit since probably the majority of patches out there are not using linked faders.

**Comment by Petervos2018** [comment]
Sorry ? ;)

> I really hate it when patch compatibility is compromised

**Comment by MarcBoule** [comment]
Ok, I updated the builds and Omri's patch (and other older patches with no linked faders) is now correctly loaded. Patches with linked faders have to be re-opened, faders adjusted to desired positions, and then patch saved. To answer your other question, this change should have no effect on gain adjust, which should be working perfectly. 

If you see anything weird, please let me know. Thanks for reporting this!
