### ISSUE TITLE
Retain PatchMaster mappings across copy & paste

### ISSUE THREAD

**Issue by grough** [MarcBoule/MindMeldModular#104]
Hi there - when I select a group of modules in my patch (including a PatchMaster) then "Save selection as", then later "Import selection", it seems the PatchMaster mappings in the imported selection no longer work. It would be nice if an imported selection could have all the mappings intact. I guess this is a limitation of Rack, rather than PatchMaster. Just wanted to raise the issue in case a solution could eventually be possible. Thanks for your excellent modules.

**Comment by nay-seven** [comment]
you need strip module..
check [the manual ](https://github.com/MarcBoule/MindMeldModular#patchmaster)

"Preserving mappings in saved selections
In order to preserve mappings in saved selections, they should be recalled using Stoermelder's S++ module. Mappings are also preserved when using Stoermelder's Strip module.

**Comment by Torinbob** [comment]
Unfortunately Rack does not preserve midi mappings when importing saved selections.

To compensate for this, Ben Stoermelder created a new module in his Pack One plugin called S++. 

S++ is based on his earlier Strip, but allows multi-row Rack selections to be imported with midi mapping intact (whereas Strip only allows for single row Strips)

To use it, highlight the modules you want to save as a selection in Rack as normal and do a right-click 'Save selection as"

Then to import, place an instance of S++ in your patch. right-click on it and do a 'Selection > Import"
