### ISSUE TITLE
Mixmaster bug

### ISSUE THREAD

**Issue by studio67** [MarcBoule/MindMeldModular#11]
Please read my post on the VCV rack github page.. found a Strange bug in mixmaster. You can download the log and template file from the VCV github page.
https://github.com/VCVRack/Rack/issues/1616

**Comment by MarcBoule** [comment]
Hi, unfortunately the log does not show anything that can help focus in on the problem (no error messages). I can't run your patch since I don't have the commercial modules you are using, but my gut feeling is that it is probably not a problem with MixMaster since Omri has been having similar issues (he mentioned it in one of his stream a while back), and from my experiments with modules, and a test I have started with him, I don't think it is the MixMaster. 

Since it's a strange and intermittent bug, I probably will not be able to convince you of this, since your test seems to point to MixMaster, but at this point the only thing I can suggest is to in effect not use MixMaster, and keep an eye out for this bug in case you get it again. There is a module that lots of people use, that you have in your setup, and if ever the bug happens in the future and you are not using MixMaster, I would greatly appreciate a followup.

If ever you have a version of your patch that has the crash, and doesn't use the paid modules from Creative Suite and Hora, I could probably try it and give you some more feedback.

Thanks for posting the issue.

**Comment by MarcBoule** [comment]
If you want to contact me privately, I will mention the module I suspect is the problem, and then you can try your test with MixMaster, but replacing the suspect module with something else. I prefer not to mention the module/developper publicly, since I can't be 100% sure it's an issue with their module, it's such a weird and intermittent problem, and it affects other modules as well (I suspect a memory leak).

**Comment by studio67** [comment]
Hi Marc, its ok to contact privately, and i think that mixmaster is a perfect build, but it's a combination of something that i can't find. Strange is when i swap the mixer the bug is gone...
Contact me at info@studio67.nl

**Comment by MarcBoule** [comment]
(email sent)

**Comment by studio67** [comment]
Still running my template here 😎 such so small bug and a big frustration. I hope the VCV app will nail this kind of bugs with buggy modules in future versions. 

ThanX again....









Vriendelijke groeten,

José Peters
Studio67 / Grafisch ontwerp
m. +31622203487
e. info@studio67.nl
w. www.studio67.nl
a. Doornenburgsestraat 9, Gendt
 

De algemene leverings- en betalingsvoorwaarden van Studio67 zijn gedeponeerd bij de Kamer van Koophandel Centraal Gelderland.

Alle door Studio67 aangeleverde informatie blijft intellectueel eigendom van Studio67 en is uitsluitend bestemd voor de geadresseerde.Verdere verspreiding is alleen toegestaan na toestemming van Studio67. Indien deze e-mail niet voor u bestemd is, verzoeken wij u dit aan info@studio67.nl te melden en de e-mail te verwijderen.

All information enclosed within this e-mail remains the intellectual property of Studio67. All unauthorised disclosure of information is prohibited. If you are not the intended adressee for this e-mail, please destroy it and notify info@studio67.nl.
