### ISSUE TITLE
EQ Master request on scale parameter in right-click menu

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/MindMeldModular#29]
Hi Marc! I use scale function in EQs (fabfilter or ableton) quite often. It's just about reducing or increasing overall eq influence on the audio to get perfect result with the same already set curves. So if you could make some Scale slider in context menu (which can start from 100% at the middle and then go lower to 0% or higher to 200%) and connect all dB knobs to it  - that's would be great!

**Comment by MarcBoule** [comment]
Interesting, kind of like linking all four gain knobs to move them at the same time but through a menu slider. We will consider this, thanks for the suggestion Artem! You really are living up to your name: VCVRackIdeas! :-)

**Comment by MarcBoule** [comment]
In testing this out, it seems it does not respond the way we would intuitively expect it to. Here's a case to show what I mean.

![image](https://user-images.githubusercontent.com/33604154/76476992-4fbc9200-63da-11ea-9f38-da010f51bdc1.png)

In the left picture, all gains are at 0 dB except the 2nd band (LMF). Now using a slider if we were to move all gains down by 13 dB, all gains would be at -13 dB except the 2nd band, which would be at -10 dB (still dB higher, but not at all the same curve). 

Since we want the EQ screen to be normalized at 0 dB in the center, there I don't think there is a good way to do this, and I think the best for overal gain adjustments would be to use the GAIN knob at the right side of the module. 

I'll close this issue, but feel free to follow up if needed and if we think of something else, we can re-open it. Thanks again Artem!
