### ISSUE TITLE
Question: How to control filters with MIDI

### ISSUE THREAD

**Issue by Spunge** [MarcBoule/MindMeldModular#32]
Hey Marc,

First off, woooaoaaaahhh, i'm blown away by the huge amount of features of the mixmaster suite, thanks so much for the work and time you've put into this.

I'm playing around with it and was wondering if you know of a way to bind the filter cutoff to a midi control signal?

**Comment by Torinbob** [comment]
Hi Spunge

Steve here (Marc's partner in MindMeld).

I believe the short answer to your question is no unfortunately. Items in the track menus can't be mapped.

Those filters are really designed as set and forget mixing utility filters rather than creative tools. Best just use a proper filter module if you want to control it.

Glad to hear you are enjoying the mixer! it was a labour of love to develop it. :)

**Comment by MarcBoule** [comment]
Hi Spunge, Steve and I thought this over some more and have tried to expose the filters as Rack parameters in those small filter lights on the main panel, so that we can now map to them. If you would like to test this, please let me know what platform you are on, and I'll post a build for you. Cheers!

**Comment by vcvrackideas** [comment]
Thanks Marc&Steve&Spunge! works nicely! Need to update my touchosc mixer layout to realize how it works on practice.

**Comment by Torinbob** [comment]
Just to say this feature is now implemented. You can map filters by clicking on the respective small filter LED light on the front panel below the track label.

Pre-release builds of version 1.1.6c which includes this feature can be downloaded from our releases page and the 1.1.6 release should be in the library in about a week or so.

**Comment by Spunge** [comment]
Wow, thanks so much for this quick implementation! I'll wait for the library to update.

Keep up the great work guys!
