### ISSUE TITLE
Delayed volume input

### ISSUE THREAD

**Issue by milkowski** [MarcBoule/MindMeldModular#34]
I noticed that volume input seems to delay its signal rise and does not follow exact volume value form gate output.
I'm providing archive with video examples of VCV and AS mixers audio output with MindMeld mixer for comparison. There is no difference in notes played *legato* when gate output is unchanged but as soon as notes are played *portato* and gate is triggered for each note MindMeld mixer clearly cuts ADSR attack time period.

[mix.zip](https://github.com/MarcBoule/MindMeldModular/files/4707818/mix.zip)

**Comment by Torinbob** [comment]
Hi milkowski

Thanks for getting in touch.

The track volume inputs on the MindMeld mixer are designed as Voltage Control for the faders rather than as regular linear VCAs. They are not intended to replace your regular sound shaping VCA. The idea is that you can use a linear voltage source (like Impromptu Tact for example) to control a fader (or more often a group of faders) and get exactly the same response you would get when moving the faders themselves. On the MindMeld Mixer, both the faders and their respective CV inputs are scaled to the power of 3.

The AS mixer has a linear fader and a linear CV input. The VCV mixer has a power of 2 fader and a linear CV input.

The power of 3 CV inputs on our mixer have a response that is quite similar to exponential and the VCV ADSR you are using is an exponential envelope already - so the reason for the shortening of the attack time is you are doubling up on the exponential response.

An immediate solution to get the same response would be to use a regular linear VCA before the MindMeld mixer input rather than the volume CV inputs. We are considering having a linear response on the volume inputs as a user option in future though.

**Comment by MarcBoule** [comment]
The option has been added; we should be putting up pre-next-release builds within the week if ever you are in position to try it out (or just pull if you are building plugins). Thanks for mentioning this item.

**Comment by milkowski** [comment]
@MarcBoule @Torinbob Thank you very much for your detailed response. This is great! I'm definitly interested in trying it out.

**Comment by MarcBoule** [comment]
Builds are available here if you want to try it out. The option is called "Vol CV inputs" and is located in the module's main menu, and to get the behavior you want, you will need to select "Linear".

https://github.com/MarcBoule/MindMeldModular/releases/tag/v1.1.6b

If you see anything weird, please let us know, but for now I think we can close the issue. Cheers!

**Comment by milkowski** [comment]
Hi @MarcBoule 

I tested provided pre-release binary. It is definitely better but not quite there yet. The attack time is still missing if volume signal is rising from zero, if it is rising from higher level it may work now, but in general it still feels delayed.
I do not know if it is intended by design (as @Torinbob wrote) or it should behave like regular VCA in linear mode now.

I'm attaching another short video for comparison.
[mix-mm2.zip](https://github.com/MarcBoule/MindMeldModular/files/4725442/mix-mm2.zip)

**Comment by MarcBoule** [comment]
Thanks for the video and followup, we did indeed have another adjustment to make which got by us: the anti-pop slew limiters on the faders and their CV inputs were a bit too agressive, which was ok before the VCA option was added, but now it has been adjusted as it needed to be. It might get tweaked so more, but the builds have been updated, if you don't mind downloading again, you should see that it's much more responsive now. Thanks again!

**Comment by milkowski** [comment]
Thanks @MarcBoule for your effort! I made another comparison. The response is improved but there is still some slight initial muting. I'm attaching the result as usual.
[Mix-Mm3.zip](https://github.com/MarcBoule/MindMeldModular/files/4733275/Mix-Mm3.zip)

**Comment by MarcBoule** [comment]
You have good ears :-)
Here's a visual comparison of MM and VCV Mixer, as extracted from your video (MixMaster top, VCV bottom). 
![image](https://user-images.githubusercontent.com/33604154/83873844-8583c500-a702-11ea-8c7a-a29dd715d88d.png)
Thanks for your patience with this, looks like we do need to tweak it more.

**Comment by milkowski** [comment]
BTW the setup I'm using for this test is just standard new VCV Rack template with square wave output instead of triangle in VCO and attack time lowered to minimum in ADSR. You should be able to reproduce the same wave output as above from there.

**Comment by Torinbob** [comment]
Hi

This is now implemented in the latest build on our releases page. Response now should be as expected.

Please try it out and let us know what you think. 

thanks
Steve

**Comment by milkowski** [comment]
Hi,

I just verified that everything works as expected, there is no audible difference to other VCAs in linear mode. Thank you very much @MarcBoule and @Torinbob for your great work! 

Now this is my favorite mixing tool. :)

**Comment by Torinbob** [comment]
Excellent - thanks for reporting back :)
