### ISSUE TITLE
Mouse scroll wheel in context menu (for filter and ets)

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/MindMeldModular#41]
Hi Marc & Steve! This is about the workflow. I'm now using Spin+Sail modules from Stoermelder which allow to do mousewheel control over the knobs. And this would be great if you can do some internal tweak in mixmaster context menus - I just intuitively hovering around filter's sliders and do some scrolling but of course no effect) I think it would be pretty handy and fast tweaking even for users that don't gonna use stoermelders modules at all. And yeah while we're in context menu mousewheel doesn't affect rack's scrolling feature which can be pretty nice place to realize that (if possible internally of course). Cheers! ;-)

**Comment by MarcBoule** [comment]
For track filters at least, you can already do this now if you turn on tool tips and hover over the filter lights and then mousewheel those with Spin+Sail. Granted they are not very big, so the mouse has to be well positioned, but it's a workaround since I don't think it's technically feasible to make Rack parameters in the menu, and almost all of those settings are not even rack parameters to begin with, so it would be quite a huge thing to implement.
