### ISSUE TITLE
Poly Volume and Pan CV control inputs in MixMasters

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/MindMeldModular#44]
Hey guys! Just would like to hear your opinion on this suggestion. ) The big one doesn't have any room for this anyway but maybe tiny expander could really helps a lot. The reason why I'm asking for it is there are already so many poly controls modules and they can make fast connection with poly aux inputs or so but pan and volume are still in the separated state so splitter needs kinda thing. Cheers! 
(of course I thought about midi mapping options via CV-MAP module but in terms of mixing snapshot it would be nice to use existed faders\knobs like an offset on the mixer itself and do automation via CV)

**Comment by Torinbob** [comment]
Hey Artem,

Marc has now coded it so that the Pan and Vol CV inputs on Track 1 can accept a poly signal. If a poly signal is detected in track 1, it will spread that modulation across all 8/16 tracks. If a modulation Pan/Vol mod source is plugged into one of the other tracks, it will override the modulation from the Poly signal (so you can have most tracks modulated by the poly source, but have some modulated by their own direct source).

You can do a build and check it out :)

Steve

**Comment by vcvrackideas** [comment]
Thanks guys! Working as expected. I'm also trying to say something about same behavior on the first group (at least in big bro mixmaster) or if we're talking about junior distribute 10 channels in poly connection to the first channel to two of the groups as well.
