### ISSUE TITLE
Individual positions of linked faders are not stored in the undo history

### ISSUE THREAD

**Issue by anlexmatos** [MarcBoule/MindMeldModular#48]
To reproduce:

1. Set two faders to different positions
![image](https://user-images.githubusercontent.com/12039110/88007385-e3664380-cadb-11ea-9c20-905d91385472.png)

2. Link the two faders
![image](https://user-images.githubusercontent.com/12039110/88007428-f711aa00-cadb-11ea-8212-d6581ad2ecb2.png)

3. Drag the fader with the higher setting down to the bottom
![image](https://user-images.githubusercontent.com/12039110/88007466-07c22000-cadc-11ea-98df-21bdfd4b4619.png)

4. Press undo
![image](https://user-images.githubusercontent.com/12039110/88007483-13154b80-cadc-11ea-9825-64a3616ed0c2.png)

**Comment by MarcBoule** [comment]
Hi, 
Thanks for the detailed and reproducible report, it's much appreciated. Exceptionnaly in this case though, I don't think a fix will be easily implementable since linked faders are quite complicated in the code, and it would be a mess to handle given those are Rack parameters that are mappable. So in this rare case I think we'll have to leave the current behavior as is unfortunately. 
Best,
Marc
