### ISSUE TITLE
Mixmaster (& Jr) poly-gate issue on channel 1

### ISSUE THREAD

**Issue by Eurikon** [MarcBoule/MindMeldModular#55]
Hello my friends! 
Me again :D 

I am seeing some strange behavior on the Mixmaster (& Jr) when connecting a poly-gate to channel 1 volume CV.

The incoming gates will be spread out over the other channels. This doesn't happen when the same poly-gate is connected to any other channel higher then channel 1.

Can you reproduce this?

**Comment by MarcBoule** [comment]
Hi Latif,
This is normal behavior, as channel 1 is special and has poly spreading.
![image](https://user-images.githubusercontent.com/33604154/96367213-69654b00-111a-11eb-8d02-9d7b52589b51.png)
The same happens for the audio and panning in channel 1, they have poly spread also, so this is by design. I think the solution would be to use a VCV Sum module (not very practical), or make sure channel 1 is not using any polyphonic cables.
Cheers,
Marc

**Comment by Eurikon** [comment]
Alright Marc thanks! I had never inserted a poly-gate into the V cv yet, so it was new to me :) 
I will take that into account then.

You say this is normal for audio as well? 
But i never seen audio being spread out over the first 4 channels, when i connect a poly audio to channel 1.

Or are you saying something different?

**Comment by MarcBoule** [comment]
Ah, no it's my mistake: poly spread is done for pan on channel 1, but not audio so you are correct for that :-)

**Comment by Eurikon** [comment]
Ok got it!
i will take the gate thingy in consideration when working with it.
Thanks Marc :)

**Comment by MarcBoule** [comment]
My pleasure, Cheers Latif!
