### ISSUE TITLE
Feature Request: HUI/MCU control

### ISSUE THREAD

**Issue by benirose** [MarcBoule/MindMeldModular#59]
I'm not sure if there's a drop in library for something like this, at least for an API to react to for the MIDI messages, but I would easily pay for MCU integration of the mixers and expanders.

**Comment by MarcBoule** [comment]
Hi,

It would be a fun project, but unfortunately I think it will have to be contributed by someone else since on my side I don't have much time unfortunately (and I also don't have an MCU compatible controller to experiment with). 

But just for fun I researched it a bit, and from my novice understanding, the advantage of adding MCU compatible MIDI messages to MixMaster/AuxSpander would be mainly for getting the track names out to the MCU device, and also (potentially?) control the motorized knobs for when we reload patches? For the track names, it would not be too difficult I think, from what I have seen here:
https://github.com/Silhm/bcf-scribble-strips/wiki/Understanding-Mackie-Control-Protocol

In the other direction, I guess it could also save a whole lot of MIDI mapping steps, but with patience, we've seen a few people map complex controllers to the MixMaster/AuxSpander, and with the use of templates, it could be less painful to manage. 

Cheers,

Marc

**Comment by benirose** [comment]
Definitely understandable. I'm more keen on the reduction of MIDI Mapping. I just mapped my LaunchControl XL to the MixMaster Jr and it was quite a chore. Also the benefit of HUI devices is that you get banking which you can't get from straight MIDI mapping. I might take a look at the protocol to see how tricky it might be, but I do feel a bit in over my head.

**Comment by MarcBoule** [comment]
Hi, unfortunatley we will close this issue since it's not something we are ready to enage in for the forseable future.
