### ISSUE TITLE
BassMaster Width can be set to decimal (x.xx) but display only shoes full integers

### ISSUE THREAD

**Issue by fractalgee** [MarcBoule/MindMeldModular#60]
BassMaster 1.1.12 (Rack 1.1.6) on Win 10 

The Width setting can be set to decimals (x.xx) with the knob but the displays below them only show whole numbers
Just noticed so does the crossover knob/display.

Can they please be fixed to show the x.xx in the displays, so one has a visual ref of exact setting?

**Comment by MarcBoule** [comment]
Hi, since there is not much room and we want to keep the visual load to a minimum, the most we will be able to do is 1 decimal place, like this:

![image](https://user-images.githubusercontent.com/33604154/103788980-7acd3d80-500d-11eb-99a3-98a1ca539a0b.png)

This will be in the next update, but we likely wait until we have more changes before submitting a new version to the library. Thanks!

**Comment by fractalgee** [comment]
if you round properly up or down I'm good with one decimal, just to spot
when things aren't set to exact values. Thanks, and take whatever time
needed, no rush needed, just irked me enough yesterday to post this issue
....  Happy and much better 2021 that the turd of a year just behind us.....

**Comment by MarcBoule** [comment]
this has been pushed in the current update, and should be in the library very soon
