### ISSUE TITLE
Feature Request: Mid-Side Stereo mode

### ISSUE THREAD

**Issue by z-plane** [MarcBoule/MindMeldModular#62]
Would be cool to have a mid-side stereo mode which you can set per channel. pan left sends the signal to mono, pan right sends to the sides.

Merci!

**Comment by MarcBoule** [comment]
Hi, it's an interesting idea, but the mixer is already quite packed for mid-side, we opted to offer it as a separate module that you can use only on the tracks that need it. It's called bass master:

![image](https://user-images.githubusercontent.com/33604154/114931990-fb69ba00-9e04-11eb-9446-158bab2bf8a3.png)

Although it does not mention mid-side, it is in fact a dual band Mid-Side processor. At 0% it's full mid, at 100% it's normal, and at 200% it is a stereo widener. Perhaps it does not do everything you want, but unfortunately it will have to be done using external modules since we will likely not be adding anymore features to MixMaster. Cheers!

**Comment by MarcBoule** [comment]
Salut, I just remembered we have stere width also in the track menus if you want. It's just like Bass mater, but full band: At 0% it's full mono, at 100% it's normal stereo, and at 200% it is a stereo widener. If you want actual mid-side procesing, then the best would be to use the VCV Mid-Side module, so you can acess the separate mid and side signals.

**Comment by z-plane** [comment]
Merci, I was hoping to be able to achieve the VCV mid-side module but within the channel strip (save on modules...). Admittedly this request is pretty niche in terms of application, but I thought it could be useful to create interesting stereo effects beyond usual stereo tricks...
