### ISSUE TITLE
ShapeMaster feature request - voltage range sliders

### ISSUE THREAD

**Issue by ContemporaryInsanity** [MarcBoule/MindMeldModular#66]
I have a 'SM as a quantized sequencer' use case where I'd like a voltage range of -2v to 0v.
As is, I can't do that 'in the module' as we're limited to one of nine predefined voltage ranges.
Upper & lower voltage range sliders in the range menu would remove this limitation.

**Comment by MarcBoule** [comment]
This would require many internal changes, and we are unfortunately not going to go with this suggestion.

**Comment by ContemporaryInsanity** [comment]
That's disappointing.

Unless you've made catastrophic design decisions, which from the amazing quality of your work I doubt very much, I don't buy this.  Were this open source I expect I'd be able to implement my request in a few hours max.

This is one hell of a module, all I want to do is help make it even better.

You don't want to do it for whatever reasons, fair enough, but please don't insult my intelligence as to how difficult it might be.

Still a happy customer wishing you all the best :)

**Comment by sinan166** [comment]
> 
> 
> That's disappointing.
> 
> Unless you've made catastrophic design decisions, which from the amazing quality of your work I doubt very much, I don't buy this. Were this open source I expect I'd be able to implement my request in a few hours max.
> 
> This is one hell of a module, all I want to do is help make it even better.
> 
> You don't want to do it for whatever reasons, fair enough, but please don't insult my intelligence as to how difficult it might be.
> 
> Still a happy customer wishing you all the best :)

Wow someone got sand in their vagina !

**Comment by Torinbob** [comment]
> You don't want to do it for whatever reasons, fair enough, but please don't insult my intelligence as to how difficult it might be.

It's really not as simple as it appears as the range setting goes quite deep. It's not just a case of adding sliders and them setting the range and drawing a grid.

To give one example, you said "I'd like a voltage range of -2v to 0v"

OK, so let's say we had set that range. Now we go into random settings where we have sliders for 0V ratio and a MaxV ratio. But hang on... now 0V IS our MaxV! so what would those sliders do when 0V and MaxV are the same thing? and what would setting them differently do? And how would you make random gate patterns that rely on those sliders controlling the two range extremes when they now control the same value? and even if there were answers to these questions, how would we expect users to understand it because it would not be intuitive?

For this reason among others it's not somewhere we want to go because it gets messy. Particularly as this is modular and it is super easy to add a -1V offset to +/- 1V range to get what you want.
