### ISSUE TITLE
Linux font rendering

### ISSUE THREAD

**Issue by Gavilaan** [MarcBoule/MindMeldModular#69]
I switched to Linux recently and the fonts of the MindMeld Modules looking ugly. Maybe it's just because i haven't installed the used fonts. Can anyone help me with that?
Thanks for the good modules, i like them very much.
Regards
Gav

**Comment by MarcBoule** [comment]
Hi, 

We will need a bit more information to investigate further. 

* What version of Linux are you using?
* What module is causing the problem? You will notice that the MixMaster uses a different font than the other ones (EqMaster, BassMaster, ShapeMaster), so we would need to know more specifically where the problem is located.
* MindMeld have been used in Linux for a while now, so is this a recent problem and you have been using the modules successfully in the past, or have you installed MindMeld recentely for the first time?
* Could you provide a screen shot showing the problem?

Normally you should not need to install the font (it's in the `/res/fonts` folder of the plugin if ever you want to test it elsewhere in your Linux, but the Module will load the font automatically and use it internally all by itself.

Sorry for all the questions, but it's hard to debug this without more info :-)

Cheers!

**Comment by MarcBoule** [comment]
Without any more info, we won't be able to go further on this one, but if you have more details to supply, feel free to follow up and we'll re-open the issue.
