### ISSUE TITLE
Enhancement Requests

### ISSUE THREAD

**Issue by mikeloveridge** [MarcBoule/MindMeldModular#7]
Hi and again, thanks for developing this mixer. I'm including a list of features I would like to see. Not in any priority and none are issues and mostly to think about and consider.  Please take these in the spirit of requests only.  I don't want my suggestions taken the wrong way.

Layout
1. I would be nice see the Aux module be full width instead of 2 rows and then I would put it above the mixer rather than to the side and the channels would line up in a complete row just like a real mixer would look.  This may not work because of the need for linked modules to be to the sides.
2. Have an 8-channel version. I like the 16!, but I think there maybe more who might use use an 8 channel version and you can chain the mixers it looks like.
3. Would like the channel labeling to handle a few more characters. Maybe 2 lines of text. Don't know. Personally, I don't have problems with large modules in VCV since it's not a physical rack and you can scroll and zoom.

Functionality
1. I would like to be able to map the gain inputs for each channel so that I can use the knob on my control surface to adjust the gain. I love that your mixer even has gain adjustments available! No other mixer I've used in VCV has this.
2. Would love to see some built in processing like limiting and/or compression for each channel. You already have some of this with the HPF and HPF cutoffs which are typical on all mixers. Although, you are the first to do this in VCV. Thanks! I'm sure I could do this with some inserts, but it would make for a bulky patch. 
3. The layout is not clear how I would use the Poly Inserts. Maybe some labeling that the top 3 inserts are the send and the bottom are the returns would help.
4. I love that you have buses available for the the groups so I can send them to effects as a group and not individually. What would be also awesome would be a way to chain some of the effects. I'm not sure how to accomplish this. What I mean by this is if I send a channel to a delay module, I would like a way to send the return of the delay on to the reverb send so that the delayed effects also have reverb. I see a way of doing that by sending the return of the effects bus to another channel and sending that channel to the reverb effect. This is a common method on most analog mixers. Most digital mixers would allow me to chain the delay effect to the reverb effect. I can't think of way for you to handle this elegantly though. The only way to accomplish this is to restructure the whole mixer as a digital mixer rather than analog. So this is mostly food for thought. Keeping it in an analog style is easier for most users that are unfamiliar with mixers in general and probably the best fit for the VCV philosophy in general. I'm just rambling now.

Just saw the feature where I can copy the settings of one channel to another. Love it! I sometimes need to move the inputs to another channel and this will make it a breeze!
Thanks!
Mike

**Comment by Torinbob** [comment]
Hi Mike

Regarding your points..

Layout

1. Can't be done. VCV Rack expanders only work when placed to the left or right side of the main module. There is no support for expanders to be above or below.

2. We might consider an 8 channel version but there are already some good 8 channel mixers in VCV. Foremost on our minds is VCV Console - a commercial plugin plugin the sales of which help support the VCV platform itself - we would need to think very carefully before coming out with an 8 channel version of our mixer that would directly compete with it. Right now we are focussed on producing some other modules which break new ground.

3. Regarding more characters on the labels - 2 lines is definitely not an option as there simply isn't the space without reducing say the size of the VUs which is not something we'd want to do. Nor can the displays go any wider. We think 4 characters is enough to give you a decent visual cue for which signal is going into the channel. Having more characters where only 4 are visible but the rest scroll across when hovered over is an idea we had and it might be something we look at in a later version but can't promise anything there.

Functionality

1. Unfortunately it's simply not possible to map anything in the track menus. Would be nice if it was... the controls in the track menus are considered as set-and-forget utilities rather than performance controls though - in the case of the gain, for balancing levels before you start mixing. Ideally all this stuff would be on the front panel but when trying to fit all the functionality of a studio mixing desk into 3U Eurorack format, there are definitely some compromises that need to be made due to space.

2. Processors like compression and EQ are definitely something we are investigating and have some ideas about - watch this space!

3. The top 3 poly insert jacks have a black background which is a standard VCV depiction for outputs - will look into whether this can be made any clearer though.

4. It's really easy to put FX on your FX with MixMaster. Just route the Aux return to a Group. Say for example you have a reverb on Aux A and a delay on AuxB. Route the AuxB delay return to a group (lets say you choose to route it to group 4). Now you can add reverb to that using the Aux A send on Group 4.
Given the potential for feedback loops when routing returns to group and adding more sends, MixMaster has built in feedback protection. In this case where you routed the Aux B return to group 4, we automatically mute the Aux B send on Group 4, so you can't add more of the same effect and create a feedback loop (which gets nasty very quickly with reverbs etc). You can however turn this feedback protection off in the global menu - see the "Routing returns to group" settings. - so it is possible to add more delay to your delay etc with this protection turned off.

**Comment by mikeloveridge** [comment]
Thanks for taking the time to respond to my suggestions and clearing up a
few things as well.  Much appreciated!
Mike
