### ISSUE TITLE
Alternate version of amount (sustain like behavior) 

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/MindMeldModular#71]
Hi Marc! By now amount knob decreasing all existed envelope level which is perfectly right. But what if we would get something alternative option in channels option to increase the bottom level of the envelope instead and when it would be fully up we will get 10volts or full upper line? What I mean it's like an envelope compression when lower levels become high at full values. I think it would be useful for such things as volume automation or so. By now I should apply some tricky attenuvertion to achieve that (probably) but if you're guys will find this option useful it would be amazingly great. Cheers!

**Comment by MarcBoule** [comment]
Hi Artem, the amount knob is a bit more complicated that it seems, since it does actually bring bottom parts up when reducing the amount, and the reason for this is that amount is not actually done based on the bottom of the shape, it's actually done relative to the initial voltage. So in a ducking-type enveloppe, reducing amount brings up the low voltages like this:

![image](https://user-images.githubusercontent.com/33604154/116274387-9ee59380-a750-11eb-8c76-85e6e44c7b38.png)

So since shapes can have arbitrary intitial voltages, and arbitrary min and max voltages, I'm not sure there is a consistent way to make an alternate amoun that would make sense in this context, so I think we will keep just the current version unfortunately.
