### ISSUE TITLE
ShapeMaster feature request - randomisation expander

### ISSUE THREAD

**Issue by ContemporaryInsanity** [MarcBoule/MindMeldModular#75]
Loving the randomisation abilities of SM.  It would be useful if the randomisation parameters could be exposed through an additional expander module.

Also, while I'm on randomisation, if I send a pulse to both the invert and randomise SM-CV inputs, it only inverts, no randomisation occurs.

**Comment by MarcBoule** [comment]
We took note of the random expander idea for eventual future work on ShapeMaster---you should see the list of potential improvements we have, it's not small :-)---, but in the near future I don't think we'll be adding another expander unfortunately.

For the SM-CV issue, those operations can not be combined simultaneously unfortunately, and there has to be a very small amount of time between them (since there are two different threads at play), but I made a small change such that when we get simultaneous triggers on the Random and Invert inputs (or Random and Reverse inputs), it will give higher priority to the randomization.

**Comment by ContemporaryInsanity** [comment]
Fair enough.  Would love to see the list :)

If you DO go with an additional expander in future, a recording facility would also be nice, think along the lines of my super simple vector victor module, CV In & Write In so we can record / modify CV loops in SM.
