### ISSUE TITLE
Questions: Poly Direct outputs are split 1-8, 9-16

### ISSUE THREAD

**Issue by mikeloveridge** [MarcBoule/MindMeldModular#8]
Hi!
Just curious... Why are the direct outputs that are polyphonic split into 2 groups? I'm not sure what the advantage is here and I can be missing a feature you intended. If I use the Nysthi Polyphonic Recorder, it has a single 16 channel input and so I need to split the first 8 out, the second 8 out and then merge both to 16 go to the recorder.
Just wondering. :)
Mike

**Comment by MarcBoule** [comment]
It could indeed have been possible to have all 16 Left channels in the first output jack and then all 16 Right channels in the other jack, but I guess @Torinbob (Steve) had a preference or reason for mapping like this to keep the L and R close together, and for someone using less than 8 tracks, everything fits in one cable. I guess it's an editorial choice. So I guess what you are proposing is best for mono tracks, since you would like all 16 (L) in one cable, but in the case of stereo, I think it makes more sense to have 1L, 1R, 2L, 2R, 3L, etc, thus the 1-8 and 9-16 split.

**Comment by Torinbob** [comment]
Yes, Marc is right. Each track on Mixmaster is effectively stereo so each track is two poly channels, one for Left and the other for Right.

If you treat each track as stereo then no need to do any splitting between the poly direct outs and the Poly Recorder. Just use 2 poly recorders for the 16 tracks (and another for the groups and aux)

**Comment by mikeloveridge** [comment]
Thank you for this explanation.  I wasn't even thinking stereo so now I understand. 
Thanks again for such an awesome full feature mixer!
