### ISSUE TITLE
Idea: Two EQ masters (channel eqs) - one is for MID and another for SIDE. But here is the issue..

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/MindMeldModular#88]
...we need some nice spiltter module (1|2, 1|2 and etc), and merger to connect this mad sum into one poly input of inserts (all of this using for example MID Side module of VCV which is polyphonic on all ins and outs). What do you think on it, guys?

**Comment by MarcBoule** [comment]
Hi Artem,

We've been thinking about your request, and just for documentation sake I'll post a bit of stuff here, with our proposal at the end, which we would like to get your feedback on.

So initially, the idea for 8 track does involve a whole lot of ugly routing, as shown here:

![image](https://user-images.githubusercontent.com/33604154/147489681-9177b493-c76b-4255-8253-d1bfe32a80c7.png)

But this can be optimized, since it's not a problem if some channels in VCV Mid-Side are wasted, given that Mid-Side is very low CPU. Next picture shows a functionally equivalent patch, with much less routing.

![image](https://user-images.githubusercontent.com/33604154/147489773-cc76a258-6834-43b0-acce-2874a8a849d8.png)

So now to get this really clean, we would need to make a very small module with 6 poly jacks on it, that would encompass all the routing contained in the selected (red) block below:

![image](https://user-images.githubusercontent.com/33604154/147489897-c7dad7dc-2c20-4372-8e8a-2bb52f56104a.png)

If we draw a box around the red selection, there are only 6 cables going in/out of that block, hence the idea of a simple very small module with 6 poly jacks on it.

This would then make it easier to connect 16 tracks and the groups/auxes, since in my pictures I've only been doing 8 tracks.

Does this sound ok to you?

**Comment by vcvrackideas** [comment]
Thanks guys, it looks awesome and idea with that small module is brilliant! Looking forward for it!

**Comment by MarcBoule** [comment]
The module is done and commited to gitub, here's the very small manual entry for it:

https://github.com/MarcBoule/MindMeldModular#msmelder

I don't remember if you build pluings, but if you would like a build just let us know your platform and we'll post one for you. If you can try it out and test it, and let us know if you see any bugs. Cheers!

**Comment by vcvrackideas** [comment]
> The module is done and commited to gitub, here's the very small manual entry for it:
> 
> https://github.com/MarcBoule/MindMeldModular#msmelder
> 
> I don't remember if you build pluings, but if you would like a build just let us know your platform and we'll post one for you. If you can try it out and test it, and let us know if you see any bugs. Cheers!

Thanks Marc! No worries, I can build it by myself, the only thing what I'm messing with right now is juse a New Year rush ;-) Wish you all of the best guys in New Year and thanks for this modules. Huge spreading stereo is just under precise control right now due to this one! Cheers!

**Comment by MarcBoule** [comment]
Awesome Artem! Have a good 2022 from Steve and me!
