### ISSUE TITLE
Q: Mixmaster: Mute Group does not mute effect returns

### ISSUE THREAD

**Issue by docb** [MarcBoule/MindMeldModular#89]
hi,
if the single tracks of a group have aux sends and i mute the group then i hear still the aux return signals.
similar when the group fader is down the effect returns are still there.
is this a bug or feature?
intuitively i expected that if i mute a group i don't here anything from it. 

thanks.

**Comment by MarcBoule** [comment]
It think it's because you still have sends on the tracks, and those are still going out irrespective of what you are doing in the groups. So you can either turn down all the sends on those tracks and use only the sends of the groups they are assigned to, and then it should work better, or alternately, you should check the option shown below, and it should also perhaps give you the behavior you are seeking.

In the module's main menu -> "AuxSpander" section -> in the "Aux sends" sub menu, there is an option called "groups control track send levels" (turn this on)

Hope this helps!

**Comment by docb** [comment]
setting the option does exactly the job. thanks!
