### ISSUE TITLE
ShapeMaster randomisation feature request.

### ISSUE THREAD

**Issue by ContemporaryInsanity** [MarcBoule/MindMeldModular#90]
Please consider adding a sixth slider to the randomisation settings menu to control the overall amount of randomisation applied from 0% (no change) to 100% (totally new shape).

I love using ShapeMaster randomisation to generate funky grooves with curves, I'd like to be able to subtly vary them over time.

How I imagine this working: for any randomisation amount below 100%, nodes that fall on grid-x lines would move up / down by the randomisation amount percentage, nothing else changes so any curves are also modified but preserved in place.

Equal adjacent nodes would move together thereby maintaining flat steps.

![image](https://user-images.githubusercontent.com/12547379/163683839-11bd6b8e-9aeb-4fee-bec8-f9c2e4adb0b0.png)

In the above image, for less than 100% randomisation, nodes 0/27 & 1 would move together, nodes 2 & 3 would move together, as would 4 & 5, however node 6 would move on its own as it has a curve (doesn't have an equal adjacent node), same for nodes 16, 17 & 22.  In summary, flat steps are preserved but altered, curves are also preserved but altered.

**Comment by MarcBoule** [comment]
Steve actually asked for this a few times ;-), and thinking back on it now, the only way I would perhaps consider implementing something like this, is if we added an extra option to turn on/off this feature for it to work separately from all the existing random stuff we have now. If we just plain add the feature, in my mind it's way too convoluted to have all the randomization options active at the same time (some combinations of options are actually ill-defined and inconsistent). 

We could have an extra setting in the menu called "delta mode" for example (it could be another name), which when activated, none of the settings we have now would work, and the only thing that hitting randomize would do would be to perform the randomization of nodes as you have described it above, via the new slider you proposed. So in this mode, the number of nodes and their horizontal positions, for example, would be unchanged when randomizing, and it would only move (some of) the nodes vertically as per your description. 

I'm not 100% sure I want to do this yet though, since the menu is again getting bigger and uglier, and I would likely need to make the unrelated menu items disappear/reappear according to the setting of that delta mode setting, but for the coding of this randomization, the only way I would consider it is if it's completely disjoint from all the current randomization options we have now.

**Comment by MarcBoule** [comment]
In reading your description again, I'm not sure about somehthing, and just to make sure I understand this correctly, I can see two ways of doing things. 

For example, say the percent change slider is at 20%, there are no steps and the vertical range is 0-10V. Which of these two scenarios best describe what you indend:

a) All nodes get randomly chosen vertical offsets applied to them, and these offsets are randomly sampled in the range ±2V (20% of the 10V range); 

b) 20% of the nodes (randomly chosen) are set to a new vertical value that is randomly sampled in the range 0-10V.

**Comment by ContemporaryInsanity** [comment]
Having the option of either behaviour would be most flexible, however I'd consider a) preferable as my intention is to subtly modify grooves, b) would change the groove unpredictably.

**Comment by ContemporaryInsanity** [comment]
Further, I'd ideally like quantisation to be available in conjunction with this randomisation, however I can always force a scale outside of SM if need be.

**Comment by MarcBoule** [comment]
Agreed, I was also realizing quantization can be available in this new mode also, so I'll try to make that work.

**Comment by ContemporaryInsanity** [comment]
Random thought for if you try to accommodate both options:

You could have two sliders, one to choose the percentage of nodes selected for randomisation, another to choose the amount of randomisation.

**Comment by ContemporaryInsanity** [comment]
IF you do, a 'lock' option for the nodes slider that when engaged doesn't re-randomise selected nodes would be useful, probably getting a bit carried away tough.  Just a) above would be great :)

**Comment by MarcBoule** [comment]
I was talking to Steve earlier, and we came to the same conclusion regarding two sliders, so that seems like the best idea. 

The lock option would be nice, but it's getting too complex I fear, so this one will be for the wish list only :-)

One thing also to determine is the behavior when we get near the top/bottom of the screen. Intuitivley it should always clamp the nodes into the current range, and this is probably the best way, but it would also be possible to fold it over such that it doesn't get stuck near the top/bottom for too long. For example, say a node it at 10V, and the random offsets that are generated are positive during 4 consecutive randomizations on that given node. In this case, the voltage will stay at 10V, as we kind of expect I guess, but I'm wondering if something else would be better.

**Comment by MarcBoule** [comment]
That could work, I'll see what I prefer when I get to that part of the code.

**Comment by MarcBoule** [comment]
We've completed this and put up some builds here if you want to try it:

https://github.com/MarcBoule/MindMeldModular/releases/tag/v2.1.0b

**Comment by ContemporaryInsanity** [comment]
Love the way you've implemented it!  However:

![image](https://user-images.githubusercontent.com/12547379/165144186-d518cfc0-6695-4e14-9b00-30c2fe099663.png)
![image](https://user-images.githubusercontent.com/12547379/165144541-ba4722c7-80fa-4482-8e5d-fabb66dc9ad5.png)
![image](https://user-images.githubusercontent.com/12547379/165144882-71902174-334c-425f-be7a-33745fd4a998.png)

Over three runs it always ends up flatlining after a couple of minutes, never ends up high, at least at +/-2V.  Turning vertical only off & on again gets things moving but far from ideal and unautomatable.

Random thought: you could expand the SM-CV expander to expose the randomisation options.

**Comment by MarcBoule** [comment]
What are your "Segements" and "Range" sliders set to? It doesn't seem to flatline in tests I have run, but perhaps I've overlooked something.

**Comment by ContemporaryInsanity** [comment]
Segments 100% range 4.8%.

**Comment by ContemporaryInsanity** [comment]
My initial randomisation settings from my default patch:

![image](https://user-images.githubusercontent.com/12547379/165148858-5a1c1224-943e-4a82-8d10-7ee92759f663.png)

**Comment by ContemporaryInsanity** [comment]
Ok, seems to behave better when MaxV is non zero.

**Comment by ContemporaryInsanity** [comment]
Having endless fun with this, thanks once more.  Currently sequencing frozen wasteland everlasting glottal stopper / vox inhumana with SMPro and stoermelder transit morphing vox settings, it's an ever evolving repeated alien sentence and sounds fantastic.

Great, clean implementation too, well done!

My only outstanding desire is an expander that gives CV control over rand parameters.  Until I think of something else :)

**Comment by MarcBoule** [comment]
Excellent news, thanks for the positive feedback! I don't think we will add anything to the expander unfortunately, but at least now we pushed the bar a bit further on the randomization aspect of SM :-)

**Comment by ContemporaryInsanity** [comment]
This still has a tendency to 'flatline' over time to minV, never seen it tend to maxV.

**Comment by MarcBoule** [comment]
Can you send me a miniml patch showing the fauly behavior? Also, just so you know, if by the minV / maxV concepts you are referring to you mean the sliders in the other mode (i.e. the non vertical-only, aka the original mode) then it should be known that they are not applicable in the vertical only mode. 

Here's how the vertical only mode works (it uses no sliders settings from the normal mode except quantization):
* select x% of the nodes (according to slider) and add a random offset to their vertical levels accoding to the range slider
* if the offset in the previous step overflows the top or bottom of the acceptable voltage (according to the range setting), fold back half of the overflow.

For example, if we are in a 0 to 1 V range, and we have a node at 0.8 V, and then the random offset that is generated for that node is +0.5V, we have an overflow of 0.3V; folding back half of that around the upper bound will yield a final voltage of 0.85V. 

If you see something in this method that could explain the behavior you are seeing, perhaps we can explore some other way of doing it. But as it is, I'm not sure what the problem could be.

**Comment by ContemporaryInsanity** [comment]
[SMProST.vcvs.zip](https://github.com/MarcBoule/MindMeldModular/files/8650822/SMProST.vcvs.zip)

Attached is a VCV selection that tends to flatline over time.

**Comment by ContemporaryInsanity** [comment]
Sorry, also meant to add that with minv maxv I was referring to the RANGE.

Good hunting.

**Comment by MarcBoule** [comment]
It turns out the problem was occurring because of quantization: when a note got quantized with an equidistant choice, the code would always choose the lower of the two notes to quantize to, which explains why it was gradually shifting down as the randomization was continually performed.

I have now made it a 50% chance of going up or down, when an equal choice is possible, and it seems to fix the bad behavior you found.

Here's a concrete example in your patch:

![image](https://user-images.githubusercontent.com/33604154/167520559-ab6c726c-733a-4977-ad3a-6ba29a54f2eb.png)

A D# can go two semitones down, to C#, or two semitones up, to F. If the code is deterministic and always chooses the lower note, then the randomness is skewed towards the bottom... Quite fascinating, I had not anticipated this, but it makes perfect sense now. So the trick was to do this:

https://github.com/MarcBoule/MindMeldModular/blob/master/src/ShapeMaster/Shape.cpp#L513-L517

I hope there are no other odd cases like this, but let me know if this looks ok from your side.

**Comment by MarcBoule** [comment]
Excellent :)
